// THIS FILE WAS GENERATED BY yaml2dart. EDIT IS NOT RECOMMENDED.
const name = 'var_dump';
const description =
    'Dumps details in tree from variable. Optionally exits. Can use dump() or var_dump(), or dd() for "dump and die"';
const version = '0.4.3';
const repository = 'https://github.com/insign/dart_var_dump';
const homepage = 'https://github.com/insign/dart_var_dump';
const environment = '{sdk: >=2.17.0 <3.0.0}';
const platforms = '{linux: null, macos: null, windows: null}';
const devDependencies = '{lints: ^2.0.0, test: ^1.21.0}';
const dependencies = '{all_exit_codes: ^2.1.0}';
